source:
  language:
    [
      "en",
      "nl",
      "de",
      "it",
      "fr",
      "es",
      "ru",
      "sv",
      "no",
      "da",
      "hy",
      "cy",
      "orv",
      # "qhe", code-switching
      "sl",
      # "kmr", <25, <100
      "it",
      "tr",
      "fi",
      "id",
      "uk",
      "pl",
      "pt",
      # "kk", <25, <100
      "la",
      "fro",
      # "bxr", <25, <100
      "ko",
      "et",
      "hr",
      "got",
      # "swl", sign language
      "sme",
      "pcm",
      "lv",
      "zh",
      "lt",
      "gl",
      "vi",
      "el",
      "ca",
      "cs",
      "mr",
      "eu",
      "sk",
      "ta",
      "mt",
      "grc",
      "is",
      "ur",
      "ro",
      "fa",
      "ja",
      "hu",
      "hi",
      "lzh",
      "fo",
      "sa",
      # "olo", <25, <100
      "ar",
      "wo",
      "bg",
      "te",
      # "qtd", code-switching
      "cu",
      # "hsb", <25, <100
      "ga",
      "af",
      "be",
      # "cop", <25, <100
      "sr",
      "hyw",
      "gd",
      "he",
      "ug",
    ]

target:
  task_format: "{task_name}-{language}"

  token-classification:
    udpos28: {
        dataset: "./datasets/udpos28|{language}", # dataset|subset
        language:
          [
            "en",
            "nl",
            "de",
            "it",
            "fr",
            "es",
            "ru",
            "sv",
            "no",
            "da",
            "nds",
            "akk",
            "hy",
            "cy",
            "orv",
            "sq",
            # "qhe", code-switching
            "sl",
            "gub",
            "kmr",
            "tr",
            "fi",
            "id",
            "uk",
            "pl",
            "pt",
            "kk",
            "la",
            "fro",
            "bxr",
            "urb",
            "ko",
            "et",
            "hr",
            "got",
            # "swl", sign language
            "gsw",
            "aii",
            "sme",
            "pcm",
            "lv",
            "zh",
            "tl",
            "bm",
            "lt",
            "gl",
            "vi",
            # "am", <10
            "el",
            "ca",
            # "soj", <10
            # "ess", empty (not token-level, but morpheme-level)
            "cs",
            # "bej", # no written data, phonetic-ish transcription
            "myv",
            "bho",
            "th",
            "mr",
            "eu",
            "sk",
            "quc",
            "yo",
            "wbp",
            "ta",
            "mt",
            "grc",
            "is",
            "gun",
            "ur",
            "ro",
            "fa",
            "apu",
            "ja",
            "hu",
            "hi",
            "lzh",
            "koi",
            "fo",
            "sa",
            "olo",
            "ar",
            "wo",
            "bg",
            "aqz",
            "mpu",
            "xnr",
            "br",
            "te",
            "yue",
            # "qtd", code-switching
            "cu",
            "krl",
            "hsb",
            "ajp",
            "kpv",
            "ga",
            "nyq",
            # "qfn", code-switching
            "myu",
            "gv",
            "sms",
            "af",
            "otk",
            "tpn",
            "be",
            # "cop", <10
            "sr",
            "mdf",
            "hyw",
            "gd",
            "kfm",
            "he",
            "ug",
            "ckt",
          ],
      }

model:
  type:
    ft: {}

  config:
    xlm-roberta-base: [ft]
